---
abstract: 'Module to handle PTD files in Dumper Format'
author:
  - 'Alberto Simões <ambs@cpan.org>'
build_requires:
  Compress::Zlib: 1.16
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-PTD
no_index:
  directory:
    - t
    - inc
requires:
  DBD::SQLite: 1.30
  DBI: 0
  File::Copy: 0
  File::Spec: 0
  IO::Compress::Bzip2: 2.027
  IO::Compress::Xz: 2.058
  IO::Uncompress::Bunzip2: 2.027
  IO::Uncompress::UnXz: 2.058
  List::MoreUtils: 0
  Pod::Usage: 0
  Term::ReadLine::Gnu: 1.20
  Time::HiRes: 1.2
  Unicode::CaseFold: 0
  parent: 0
  perl: 5.006
version: 1.06
