---
abstract: 'Module to handle PTD files in Dumper Format'
author:
  - 'Alberto Simoes <ambs@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-PTD
requires:
  DBD::SQLite: '0'
  DBI: '0'
  Encode: '0'
  Exporter: '0'
  File::Copy: '0'
  File::Spec::Functions: '0'
  IO::Compress::Bzip2: '2.066'
  IO::Compress::Xz: '2.066'
  IO::Uncompress::Bunzip2: '2.066'
  IO::Uncompress::UnXz: '2.066'
  List::MoreUtils: '0'
  Module::Load::Conditional: '0'
  Pod::Usage: '0'
  Term::ReadLine: '0'
  Term::ReadLine::Gnu: '0'
  Time::HiRes: '0'
  Unicode::CaseFold: '0'
  parent: '0'
  perl: '5.010'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  repository: https://natura.di.uminho.pt/svn/main/Lingua/PTD/
version: '1.13'
